name: "Test PyInstaller Binaries"
description: "Test pyinstaller binaries"
inputs:
  package_name:
    description: "The name of the package to build and test"
    required: true
  operating_system:
    description: "Operating system to set the correct binary path and extension"
    required: true
  python_version:
    description: "Python version to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.package_name }}-${{ inputs.operating_system }}-py${{ inputs.python_version }}

    - name: Unzip Artifacts
      run: |
        mkdir -p binaries
        tar -xzf ${{ inputs.package_name }}-${{ inputs.operating_system }}-py${{ inputs.python_version }}.tar.gz -C binaries
      shell: bash

    - name: Set CLI_PATH
      run: |
        CLI_PATH="${{ github.workspace }}/binaries/${{ inputs.package_name }}"
        if [ "${{ inputs.operating_system }}" == "Windows" ]; then
          CLI_PATH="${{ github.workspace }}\binaries\${{ inputs.package_name }}.exe"
        fi
        echo "CLI_PATH=$CLI_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Run portability tests
      run: |
        echo "Executing: ${{ env.CLI_PATH }}"
        git config --global user.email "actions@github.com" && git config --global user.name "github-actions" 
        poetry run pytest tests/ -m pyinstaller_binary_tests --cli_path "${{ env.CLI_PATH }}" --log-cli-level=INFO
      shell: ${{ inputs.operating_system == 'Windows' && 'cmd' || 'bash' }}
