name: "Build Windows Binary Artifacts"
description: "Build Windows specific pyinstaller binary artifacts"
inputs:
  package_name:
    description: "The name of the package"
    required: true
  artifacts_dir:
    description: "The directory to write artifacts you want to publish"
    required: true
  version:
    description: "The version to use for this artifact"

runs:
  using: "composite"
  steps:
    - name: Build binary
      shell: bash
      run: |
        poetry run poe package_windows

    - name: Package binary artifact
      shell: pwsh
      run: |
        Set-Location -Path dist\algokit\
        tar -zcf ${{ inputs.artifacts_dir }}\${{ inputs.package_name }}.tar.gz *
        echo ${{ inputs.distribution }} > .\_internal\algokit\distribution-method
        tar -zcf ${{ inputs.artifacts_dir }}\${{ inputs.package_name }}-winget.tar.gz *
        Set-Location -Path ..\..

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_name }}
        path: ${{ inputs.artifacts_dir }}\${{ inputs.package_name }}.tar.gz

    - name: Upload binary artifact (winget)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_name }}-winget
        path: ${{ inputs.artifacts_dir }}\${{ inputs.package_name }}-winget.tar.gz
