name: "Setup, Build, and Test Pyinstaller Binaries"
description: "Build, test and upload binaries to GitHub releases and/or artifacts (ensure poetry dependencies are installed before running this action)"
inputs:
  package_name:
    description: "The name of the package to build and test"
    required: true
  production_release:
    description: "Flag to determine if this is a production release"
    required: true
  operating_system:
    description: "Operating system to set the correct binary path and extension"
    required: true
  architecture:
    description: "Architecture to set the correct binary path and extension"
    required: true
  build_command:
    description: "Command to build the binaries"
    required: true
  python_version:
    description: "Python version to use"
    required: true
  distribution:
    description: "Distribution channel to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Executable
      run: ${{ inputs.build_command }}
      shell: bash

    - name: Set TEST_CLI_PATH
      run: |
        TEST_CLI_PATH="${{ github.workspace }}/dist/${{ inputs.package_name }}/${{ inputs.package_name }}"
        if [ "${{ inputs.operating_system }}" == "Windows" ]; then
          TEST_CLI_PATH="${{ github.workspace }}\dist\${{ inputs.package_name }}\${{ inputs.package_name }}.exe"
        fi
        echo "TEST_CLI_PATH=$TEST_CLI_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Run portability tests
      run: |
        echo "Executing: ${{ env.TEST_CLI_PATH }}"
        git config --global user.email "actions@github.com" && git config --global user.name "github-actions" 
        poetry run pytest tests/ -m pyinstaller_binary_tests --cli_path "${{ env.TEST_CLI_PATH }}" --log-cli-level=INFO
      shell: ${{ inputs.operating_system == 'Windows' && 'cmd' || 'bash' }}

    - name: Set release version
      shell: bash
      continue-on-error: true
      if: ${{ inputs.production_release == 'true' }}
      run: |
        echo "RELEASE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
        git describe --tags $(git rev-list --tags --max-count=1)

    - name: Zip binaries
      shell: bash
      run: |
        ls -l dist
        cd dist/algokit/
        if [ "${{ inputs.production_release }}" == "true" ]; then
          tar -zcvf ../../algokit-${{ env.RELEASE_VERSION }}-${{ inputs.operating_system }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz *
          echo ${{ inputs.distribution }} > ./_internal/algokit/distribution-method
          tar -zcvf ../../algokit-${{ env.RELEASE_VERSION }}-${{ inputs.distribution }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz *
        else
          tar -zcvf ../../algokit-${{ inputs.operating_system }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz *
        fi
        cd ../..
        ls -l

    - name: Upload binary as artifact (release)
      if: ${{ inputs.production_release == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: algokit-${{ inputs.operating_system }}-${{ inputs.architecture }}-py${{ inputs.python_version }}
        path: algokit-${{ env.RELEASE_VERSION }}-${{ inputs.operating_system }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz

    - name: Upload binary as artifact (dev)
      if: ${{ inputs.production_release != 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: algokit-${{ inputs.operating_system }}-${{ inputs.architecture }}-py${{ inputs.python_version }}
        path: algokit-${{ inputs.operating_system }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz

    - name: Upload binary as artifact (distribution)
      if: ${{ inputs.production_release == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: algokit-${{ inputs.distribution }}-${{ inputs.architecture }}-py${{ inputs.python_version }}
        path: algokit-${{ env.RELEASE_VERSION }}-${{ inputs.distribution }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz


    - name: Append binary to release
      continue-on-error: true
      if: ${{ inputs.production_release == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          algokit-${{ env.RELEASE_VERSION }}-${{ inputs.operating_system }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz
        tag_name: ${{ env.RELEASE_VERSION }}
        prerelease: ${{ contains(env.RELEASE_VERSION, 'beta') }}

    - name: Append binary to release (distribution)
      continue-on-error: true
      if: ${{ inputs.production_release == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          algokit-${{ env.RELEASE_VERSION }}-${{ inputs.distribution }}-${{ inputs.architecture }}-py${{ inputs.python_version }}.tar.gz
        tag_name: ${{ env.RELEASE_VERSION }}
        prerelease: ${{ contains(env.RELEASE_VERSION, 'beta') }}
