name: "Build macOS Binary Artifacts"
description: "Build macOS specific pyinstaller binary artifacts"
inputs:
  package_name:
    description: "The name of the package"
    required: true
  artifacts_dir:
    description: "The directory to write artifacts you want to publish"
    required: true
  version:
    description: "The version to use for this artifact"
  apple_team_id:
    description: "The Apple Team ID"
    required: true
  apple_bundle_id:
    description: "The bundle ID to be used for packaging and notarisation"
    required: true
  apple_cert_id:
    description: "The Apple Developer ID certificate ID"
    required: true
  apple_notary_user:
    description: "The Apple user to notarise the package"
    require: true
  apple_notary_password:
    description: "The Apple password to notarise the package"
    require: true

runs:
  using: "composite"
  steps:
    - name: Build binary
      shell: bash
      run: |
        poetry run poe package_mac
      env:
        APPLE_CERT_ID: ${{ inputs.apple_cert_id }}
        APPLE_BUNDLE_ID: ${{ inputs.apple_bundle_id }}

    # Workaround an issue with PyInstaller where Python.framework was incorrectly signed during the build
    - name: Codesign python.framework
      shell: bash
      run: |
        codesign --force --sign "${{ inputs.apple_cert_id }}" --timestamp "${{ github.workspace }}/dist/algokit/_internal/Python.framework"

    - name: Notarize
      uses: lando/notarize-action@v2
      with:
        appstore-connect-team-id: ${{ inputs.apple_team_id }}
        appstore-connect-username: ${{ inputs.apple_notary_user }}
        appstore-connect-password: ${{ inputs.apple_notary_password }}
        primary-bundle-id: ${{ inputs.apple_bundle_id }}
        product-path: "${{ github.workspace }}/dist/algokit"
        tool: notarytool
        verbose: true

    - name: Package binary artifact
      shell: bash
      run: |
        cd dist/algokit/
        tar -zcf ${{ inputs.artifacts_dir }}/${{ inputs.package_name }}.tar.gz *
        cd ../..

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_name }}
        path: ${{ inputs.artifacts_dir }}/${{ inputs.package_name }}.tar.gz
