name: "Python Poetry Action"
description: "An action to setup Poetry"
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - run: |
        pip install --user pipx
        pipx ensurepath
      shell: bash
    - if: ${{ inputs.poetry-version == 'latest' }}
      run: |
        pipx install poetry
      shell: bash
    - if: ${{ inputs.poetry-version != 'latest' }}
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo "full_version=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')" >> $GITHUB_OUTPUT

    - name: Setup poetry cache
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}-${{ runner.os }}-${{ steps.full-python-version.outputs.full_version }}
