name: "Python Poetry Action"
description: "An action to setup Poetry"
runs:
  using: "composite"
  steps:
    # A workaround for pipx isn't installed on M1 runner.
    # We should remove it after this issue is resolved.
    # https://github.com/actions/runner-images/issues/9256
    - if: ${{ runner.os == 'macOS' && runner.arch == 'ARM64' }}
      run: |
        pip install poetry
      shell: bash

    - if: ${{ runner.os != 'macOS' || runner.arch != 'ARM64' }}
      run: |
        pip install --user pipx
        pipx ensurepath
        pipx install poetry ${{ runner.os == 'macOS' && '--python "$Python_ROOT_DIR/bin/python"' || '' }}
      shell: bash

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo "full_version=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')" >> $GITHUB_OUTPUT

    - name: Setup poetry cache
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.full-python-version.outputs.full_version }}
