name: "Install Apple Developer ID certificate"
description: "Install Apple Developer ID certificate to macos-build keychain"
inputs:
  cert_data:
    description: "Base64 string represents the Apple developer ID certificate"
    required: true
  cert_password:
    description: "The password to unlock the Apple developer ID certificate"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install cert
      shell: bash
      env:
        APPLE_CERT_DATA: ${{ inputs.cert_data }}
        APPLE_CERT_PASSWORD: ${{ inputs.cert_password }}
      run: |
        # Export certs
        echo "$APPLE_CERT_DATA" | base64 --decode > /tmp/certs.p12

        # Create keychain
        security create-keychain -p actions macos-build.keychain
        security default-keychain -s macos-build.keychain
        security unlock-keychain -p actions macos-build.keychain
        security set-keychain-settings -t 3600 -u macos-build.keychain
        echo "Keychain created"

        # Import certs to keychain
        security import /tmp/certs.p12 -k ~/Library/Keychains/macos-build.keychain -P "$APPLE_CERT_PASSWORD" -T /usr/bin/codesign -T /usr/bin/productsign
        echo "Cert imported"

        # Key signing
        security set-key-partition-list -S apple-tool:,apple: -s -k actions macos-build.keychain
        echo "Key signed"

        # Delete temp file
        rm /tmp/certs.p12
        echo "Done"
