name: Check Python Code

on:
  workflow_call:

jobs:
  check-python:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: ./.github/actions/setup-uv
        with:
          extra-sync-args: "--group docs"

      - name: Audit with pip-audit
        run: |
          set -o pipefail
          uv export --no-dev --no-group docs --no-emit-project -o requirements.txt
          uv run pip-audit -r requirements.txt

      - name: Check formatting with Ruff
        run: uv run ruff format --check .

      - name: Check linting with Ruff
        run: uv run ruff check .

      - name: Check types with mypy
        run: uv run mypy

      - name: Check docs are up to date
        run: |
          set -o pipefail
          uv run poe docs-cli
          [ $(git status --porcelain docs/ | wc -l) -eq "0" ]
