name: Deploy Docs Preview

on:
  push:
    branches:
      - docs/starlight-migration

concurrency:
  group: deploy-docs
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs-preview:
    name: Deploy Documentation Preview
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build documentation
        uses: ./.github/actions/build-docs

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4