name: Fork Sync

on:
  push:
    branches:
      - fork-sync

concurrency: release

permissions:
  contents: write
  packages: read

jobs:
  fork-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync winget-pkgs fork
        run: gh auth refresh -s workflow --with-token && gh repo sync algofoundation/winget-pkgs -b master
        env:
          GH_TOKEN: ${{ secrets.WINGET_GITHUB_TOKEN }}
