name: Test LocalNet with Podman

on: [workflow_call]

jobs:
  build-python:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: gacts/install-podman@v1
        #with:
        #  kind: unstable # `testing` by default
        #  qemu: true # `false` by default

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry

      - name: Install dependencies
        # TODO: remove fixed pipx dependency once 3.12 compatibility is addressed
        # track here -> https://github.com/crytic/tealer/pull/209
        run: poetry install --no-interaction

      - name: Configure Podman
        run: algokit localnet config podman

      - name: Update and Reset Podman
        run: algokit localnet reset --update

      - name: Reset Podman
        run: algokit localnet reset

      - name: Check Podman Status
        run: algokit localnet status

      - name: Stop Podman
        run: algokit localnet stop

      - name: Verify Podman Status
        run: algokit localnet status
