name: Release Production

on: workflow_dispatch

concurrency: release

permissions:
  contents: write
  packages: read

jobs:
  # run_ci:

  continuous_deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "main" # note, user can select a branch when running this action, but we force it back to main

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Release
        run: |
          poetry run semantic-release \
            publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: Upload artifact - using Python 3.10 on ubuntu-latest
        uses: actions/upload-artifact@v3
        with:
          name: algokit-cli
          path: dist/algokit-*-py3-none-any.whl
          if-no-files-found: error
