name: Test Pyinstaller binaries

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  build-python:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry

      - uses: actions/cache@v4
        name: Setup poetry cache
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}-${{ matrix.os }}-${{ inputs.python_version }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test linux binary
        uses: ./.github/actions/test-binaries
        with:
          package_name: "algokit"
          operating_system: ${{ runner.os }}
          python_version: ${{ inputs.python_version }}
